### ISSUE TITLE
SSR coverpage

### ISSUE THREAD

**Issue by rnback** [QingWei-Li/docsify#273]
I noticed the `_coverpage.md` is not rendered on the server side when using `SSR` mode.
I tried to implement the SSR by copying the logic the logic for the `_navbar.md`, but it didn't work.
Any ideas?

**Comment by soulfly** [comment]
Is it completely fixed?

I still just see a background and 'undefined' text in the center of a cover page
<img width="1052" alt="docsify_ssr" src="https://user-images.githubusercontent.com/373137/41287481-84c509a4-6e4b-11e8-92ce-b4a98dd31e5d.png">

**Comment by soulfly** [comment]
When I do 

`docsify start . -c ssr.config.js`

and then open http://localhost:4000 for the 1st time - it says 'undefined'.
Then when I go to some page and then back to the Cover page - it works correctly

I fixed this by modifying the `initFetch` function:

```
    // callHook(vm, 'doneEach');
    // callHook(vm, 'ready');

    vm.$fetch(function (_) {
      callHook(vm, 'doneEach');
      return callHook(vm, 'ready');
    });
```

because from my understanding, the `$fetch` function is not fired on SSR mode when you open your site for the first time

@QingWei-Li could you please clarify it

**Comment by soulfly** [comment]
So looks like it's still not working when use `docsify start`

Also, when use the `docsify-server-renderer` - there is an issue when the `coverpage` config is boolean (e.g. true)

It's simply no case for a boolean type in the fix - it just goes to `else` part which actually waits for an object, not a boolean 
https://github.com/docsifyjs/docsify/commit/8b132d2d099366bf48e8f36689c0f0e59f2ca360
