### ISSUE TITLE
disable/hide sidebar at onload

### ISSUE THREAD

**Issue by initbar** [QingWei-Li/docsify#442]
Is there an option to hide or disable sidebar at onload event? I'm currently relying on custom `$('.sidebar-toggle-button').click()` to hide it, but wondering if there is native support or options.

**Comment by Xcorpio** [comment]
hi, this will not work on mobile browser

**Comment by Spencer-Scorcelletti-CK** [comment]
Interesting, how does closing the sidebar work on mobile?

**Comment by shawntabrizi** [comment]
The problem here is that the `close` class has overall strange behavior.

On a mobile screen the `close` class actually _opens_ the sidebar, while omitting it closes it.

This seems to be some hack to transition a responsive desktop site which has a sidebar to a mobile  width and auto-closing the sidebar. However, this transition does not happen by using the `close` class correctly...
